package com.devzb.tucao.dao.mapper;

import com.devzb.tucao.dao.model.TucaoItem;
import com.devzb.tucao.dao.model.TucaoItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TucaoItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    int countByExample(TucaoItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    int deleteByExample(TucaoItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    int insertSelective(TucaoItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    List<TucaoItem> selectByExample(TucaoItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    TucaoItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") TucaoItem record, @Param("example") TucaoItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    int updateByExample(@Param("record") TucaoItem record, @Param("example") TucaoItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tucao_item
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(TucaoItem record);
}