package com.devzb.self.dao.model;

import java.util.Date;

public class MetalMobile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_mobile.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_mobile.type
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_mobile.mobile
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_mobile.is_send
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private String isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_mobile.gmt_created
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_mobile.gmt_modified
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_mobile.id
     *
     * @return the value of metal_mobile.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_mobile.id
     *
     * @param id the value for metal_mobile.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_mobile.type
     *
     * @return the value of metal_mobile.type
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_mobile.type
     *
     * @param type the value for metal_mobile.type
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_mobile.mobile
     *
     * @return the value of metal_mobile.mobile
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_mobile.mobile
     *
     * @param mobile the value for metal_mobile.mobile
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_mobile.is_send
     *
     * @return the value of metal_mobile.is_send
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public String getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_mobile.is_send
     *
     * @param isSend the value for metal_mobile.is_send
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setIsSend(String isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_mobile.gmt_created
     *
     * @return the value of metal_mobile.gmt_created
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_mobile.gmt_created
     *
     * @param gmtCreated the value for metal_mobile.gmt_created
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_mobile.gmt_modified
     *
     * @return the value of metal_mobile.gmt_modified
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_mobile.gmt_modified
     *
     * @param gmtModified the value for metal_mobile.gmt_modified
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}