package com.devzb.self.dao.model;

import java.util.Date;

public class MetalSms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_sms.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_sms.mobile
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_sms.content
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_sms.gmt_created
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metal_sms.gmt_modified
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_sms.id
     *
     * @return the value of metal_sms.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_sms.id
     *
     * @param id the value for metal_sms.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_sms.mobile
     *
     * @return the value of metal_sms.mobile
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_sms.mobile
     *
     * @param mobile the value for metal_sms.mobile
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_sms.content
     *
     * @return the value of metal_sms.content
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_sms.content
     *
     * @param content the value for metal_sms.content
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_sms.gmt_created
     *
     * @return the value of metal_sms.gmt_created
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_sms.gmt_created
     *
     * @param gmtCreated the value for metal_sms.gmt_created
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metal_sms.gmt_modified
     *
     * @return the value of metal_sms.gmt_modified
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metal_sms.gmt_modified
     *
     * @param gmtModified the value for metal_sms.gmt_modified
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}