package com.devzb.self.dao.model;

public class NoteItemTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_item_tag.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_item_tag.item_id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_item_tag.tag_id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_item_tag.id
     *
     * @return the value of note_item_tag.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_item_tag.id
     *
     * @param id the value for note_item_tag.id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_item_tag.item_id
     *
     * @return the value of note_item_tag.item_id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_item_tag.item_id
     *
     * @param itemId the value for note_item_tag.item_id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_item_tag.tag_id
     *
     * @return the value of note_item_tag.tag_id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_item_tag.tag_id
     *
     * @param tagId the value for note_item_tag.tag_id
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}