package com.devzb.metal.dao.mapper;

import com.devzb.metal.dao.model.MetalMobile;
import com.devzb.metal.dao.model.MetalMobileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MetalMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    int countByExample(MetalMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    int deleteByExample(MetalMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    int insertSelective(MetalMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    List<MetalMobile> selectByExample(MetalMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    MetalMobile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") MetalMobile record, @Param("example") MetalMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    int updateByExample(@Param("record") MetalMobile record, @Param("example") MetalMobileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_mobile
     *
     * @mbggenerated Sun Jan 22 16:27:31 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(MetalMobile record);
}