package com.devzb.metal.dao.mapper;

import com.devzb.metal.dao.model.MetalZincPrice;
import com.devzb.metal.dao.model.MetalZincPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MetalZincPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    int countByExample(MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    int deleteByExample(MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    int insertSelective(MetalZincPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    List<MetalZincPrice> selectByExample(MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    MetalZincPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") MetalZincPrice record, @Param("example") MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    int updateByExample(@Param("record") MetalZincPrice record, @Param("example") MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Tue Dec 06 13:47:51 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(MetalZincPrice record);
}