package com.devzb.self.dao.mapper;

import com.devzb.self.dao.model.MetalZincPrice;
import com.devzb.self.dao.model.MetalZincPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MetalZincPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int countByExample(MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int deleteByExample(MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int insertSelective(MetalZincPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    List<MetalZincPrice> selectByExample(MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    MetalZincPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") MetalZincPrice record, @Param("example") MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int updateByExample(@Param("record") MetalZincPrice record, @Param("example") MetalZincPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metal_zinc_price
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(MetalZincPrice record);
}