package com.devzb.self.dao.mapper;

import com.devzb.self.dao.model.NoteItemTag;
import com.devzb.self.dao.model.NoteItemTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoteItemTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int countByExample(NoteItemTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int deleteByExample(NoteItemTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int insertSelective(NoteItemTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    List<NoteItemTag> selectByExample(NoteItemTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    NoteItemTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") NoteItemTag record, @Param("example") NoteItemTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int updateByExample(@Param("record") NoteItemTag record, @Param("example") NoteItemTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_item_tag
     *
     * @mbggenerated Thu Jan 19 14:06:57 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(NoteItemTag record);
}