package com.devzb.tucao.dao.model;

import java.util.Date;

public class TucaoItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tucao_item.id
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tucao_item.uid
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tucao_item.nickname
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tucao_item.content
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tucao_item.longitude
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    private Long longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tucao_item.latitude
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    private Long latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tucao_item.sort_num
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    private Long sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tucao_item.gmt_created
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    private Date gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tucao_item.id
     *
     * @return the value of tucao_item.id
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tucao_item.id
     *
     * @param id the value for tucao_item.id
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tucao_item.uid
     *
     * @return the value of tucao_item.uid
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tucao_item.uid
     *
     * @param uid the value for tucao_item.uid
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tucao_item.nickname
     *
     * @return the value of tucao_item.nickname
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tucao_item.nickname
     *
     * @param nickname the value for tucao_item.nickname
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tucao_item.content
     *
     * @return the value of tucao_item.content
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tucao_item.content
     *
     * @param content the value for tucao_item.content
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tucao_item.longitude
     *
     * @return the value of tucao_item.longitude
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public Long getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tucao_item.longitude
     *
     * @param longitude the value for tucao_item.longitude
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public void setLongitude(Long longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tucao_item.latitude
     *
     * @return the value of tucao_item.latitude
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public Long getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tucao_item.latitude
     *
     * @param latitude the value for tucao_item.latitude
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public void setLatitude(Long latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tucao_item.sort_num
     *
     * @return the value of tucao_item.sort_num
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public Long getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tucao_item.sort_num
     *
     * @param sortNum the value for tucao_item.sort_num
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public void setSortNum(Long sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tucao_item.gmt_created
     *
     * @return the value of tucao_item.gmt_created
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tucao_item.gmt_created
     *
     * @param gmtCreated the value for tucao_item.gmt_created
     *
     * @mbggenerated Wed Dec 14 11:01:11 GMT+08:00 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }
}