package com.devzb.note.dao.mapper;

import com.devzb.note.dao.model.NoteTag;
import com.devzb.note.dao.model.NoteTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoteTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    int countByExample(NoteTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    int deleteByExample(NoteTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    int insertSelective(NoteTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    List<NoteTag> selectByExample(NoteTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    NoteTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") NoteTag record, @Param("example") NoteTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    int updateByExample(@Param("record") NoteTag record, @Param("example") NoteTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(NoteTag record);
}