package com.devzb.zufang.dao.model;

import java.util.Date;

public class ZufangItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.id
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.size
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.name
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.address
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.longitude
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private Long longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.latitude
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private Long latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.price
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.contact
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.contact_phone
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.uid
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.nickname
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.content
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.sort_num
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private Long sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.gmt_created
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zufang_item.gmt_modified
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.id
     *
     * @return the value of zufang_item.id
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.id
     *
     * @param id the value for zufang_item.id
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.size
     *
     * @return the value of zufang_item.size
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.size
     *
     * @param size the value for zufang_item.size
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.name
     *
     * @return the value of zufang_item.name
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.name
     *
     * @param name the value for zufang_item.name
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.address
     *
     * @return the value of zufang_item.address
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.address
     *
     * @param address the value for zufang_item.address
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.longitude
     *
     * @return the value of zufang_item.longitude
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public Long getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.longitude
     *
     * @param longitude the value for zufang_item.longitude
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setLongitude(Long longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.latitude
     *
     * @return the value of zufang_item.latitude
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public Long getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.latitude
     *
     * @param latitude the value for zufang_item.latitude
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setLatitude(Long latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.price
     *
     * @return the value of zufang_item.price
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.price
     *
     * @param price the value for zufang_item.price
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.contact
     *
     * @return the value of zufang_item.contact
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.contact
     *
     * @param contact the value for zufang_item.contact
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.contact_phone
     *
     * @return the value of zufang_item.contact_phone
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.contact_phone
     *
     * @param contactPhone the value for zufang_item.contact_phone
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.uid
     *
     * @return the value of zufang_item.uid
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.uid
     *
     * @param uid the value for zufang_item.uid
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.nickname
     *
     * @return the value of zufang_item.nickname
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.nickname
     *
     * @param nickname the value for zufang_item.nickname
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.content
     *
     * @return the value of zufang_item.content
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.content
     *
     * @param content the value for zufang_item.content
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.sort_num
     *
     * @return the value of zufang_item.sort_num
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public Long getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.sort_num
     *
     * @param sortNum the value for zufang_item.sort_num
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setSortNum(Long sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.gmt_created
     *
     * @return the value of zufang_item.gmt_created
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.gmt_created
     *
     * @param gmtCreated the value for zufang_item.gmt_created
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zufang_item.gmt_modified
     *
     * @return the value of zufang_item.gmt_modified
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zufang_item.gmt_modified
     *
     * @param gmtModified the value for zufang_item.gmt_modified
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}