package com.devzb.zufang.dao.mapper;

import com.devzb.zufang.dao.model.ZufangItem;
import com.devzb.zufang.dao.model.ZufangItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZufangItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    int countByExample(ZufangItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    int deleteByExample(ZufangItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    int insertSelective(ZufangItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    List<ZufangItem> selectByExample(ZufangItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    ZufangItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") ZufangItem record, @Param("example") ZufangItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    int updateByExample(@Param("record") ZufangItem record, @Param("example") ZufangItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zufang_item
     *
     * @mbggenerated Thu Dec 22 13:51:42 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(ZufangItem record);
}