package com.devzb.note.dao.model;

import java.util.Date;

public class NoteTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_tag.id
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_tag.tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note_tag.gmt_created
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    private Date gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_tag.id
     *
     * @return the value of note_tag.id
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_tag.id
     *
     * @param id the value for note_tag.id
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_tag.tag
     *
     * @return the value of note_tag.tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_tag.tag
     *
     * @param tag the value for note_tag.tag
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note_tag.gmt_created
     *
     * @return the value of note_tag.gmt_created
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note_tag.gmt_created
     *
     * @param gmtCreated the value for note_tag.gmt_created
     *
     * @mbggenerated Sun Jan 22 16:30:49 GMT+08:00 2017
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }
}